- name: Build with Buildozer
        run: |
          pip install buildozer
          # Forzamos la aceptación de licencias antes de empezar
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          yes | buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_NAME_AS_DOMAIN: 1
          # Esta línea es clave para evitar errores de permisos
          BUILDOZER_WARN_ON_ROOT: 0
